// Profile: WABA — WhatsApp Business API

import type { PlanningRequest } from "./tiendanube.js";

export const WABA_PLANNING_REQUESTS: PlanningRequest[] = [
  // ─── Required for planning ────────────────────────────────────────
  {
    id: "REQ-WABA-TOKEN",
    service: "waba",
    type: "credentials",
    scopes: ["WABA_ACCESS_TOKEN"],
    purpose: "Token de acceso a la WhatsApp Business API (Graph API)",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  {
    id: "REQ-WABA-PHONE",
    service: "waba",
    type: "credentials",
    scopes: ["WABA_PHONE_NUMBER_ID"],
    purpose: "ID del numero de telefono registrado en WABA",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  {
    id: "REQ-WABA-ACCOUNT",
    service: "waba",
    type: "credentials",
    scopes: ["WABA_BUSINESS_ACCOUNT_ID"],
    purpose: "ID de la cuenta de WhatsApp Business",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  {
    id: "REQ-WABA-APP-ID",
    service: "waba",
    type: "credentials",
    scopes: ["META_APP_ID"],
    purpose: "ID de la aplicacion en Meta Developers",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  {
    id: "REQ-WABA-APP-SECRET",
    service: "waba",
    type: "credentials",
    scopes: ["META_APP_SECRET"],
    purpose: "Secret de la aplicacion en Meta Developers",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  {
    id: "REQ-WABA-WEBHOOK-VERIFY",
    service: "waba",
    type: "credentials",
    scopes: ["WEBHOOK_VERIFY_TOKEN"],
    purpose: "Token de verificacion para webhooks entrantes de Meta",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  {
    id: "REQ-WABA-WEBHOOK-URL",
    service: "waba",
    type: "credentials",
    scopes: ["WEBHOOK_CALLBACK_URL"],
    purpose: "URL publica donde Meta enviara los webhooks",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: true,
  },
  // ─── Optional ─────────────────────────────────────────────────────
  {
    id: "REQ-WABA-GRAPH-VER",
    service: "waba",
    type: "credentials",
    scopes: ["GRAPH_API_VERSION"],
    purpose: "Version de la Graph API de Meta (default v19.0)",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: false,
  },
  {
    id: "REQ-WABA-BIZ-MGR",
    service: "waba",
    type: "credentials",
    scopes: ["BUSINESS_MANAGER_ID"],
    purpose: "ID del Business Manager en Meta",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: false,
  },
  {
    id: "REQ-WABA-SYS-USER",
    service: "waba",
    type: "credentials",
    scopes: ["SYSTEM_USER_ID"],
    purpose: "ID del System User en Meta Business Manager",
    where_to_set: "Panel > Configuracion",
    validation_cmd: "",
    required_for_planning: false,
  },
];
